server:
  port: 8080

spring:
  profiles: local
  application:
    name: hackathon-ptop
  jpa:
    database: MySQl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://implementation-db.rxss.io:3306?noDatetimeStringSync=true&useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: sdaripalli
    password: JUJPSp0W1ApbHR5q4I6m
    driver-class-name: com.mysql.jdbc.Driver

rxss:
  baseUrl: https://api-stage.rxsavingssolutions.com
  maxRetries: 2
  minRetryBackOffSeconds: 2
  maxRetryBackOffSeconds: 10
  connectionTimeoutInSeconds: 10
  timeoutInSeconds: 60

logging:
  level:
    org.springframework: INFO
---